#!/bin/sh
[ -z "${CIQ_SDK_VERSION}" ] && echo 'ERROR: Missing CIQ_SDK_VERSION environment variable' && exit 1
[ -z "${XAUTHORITY}" ] && XAUTHORITY="${HOME}/.Xauthority"
exec docker run \
  --name=connectiq-sdk \
  --privileged \
  --network=host \
  --tty \
  --interactive \
  --rm=true \
  --env=DISPLAY=${DISPLAY} \
  --env=XAUTHORITY=/home/ciq/.Xauthority \
  --device=/dev/dri:/dev/dri \
  --volume=/tmp/.X11-unix:/tmp/.X11-unix:rw \
  --volume=${XAUTHORITY}:/home/ciq/.Xauthority:ro \
  ${CIQ_SRC_DIR:+--volume=${CIQ_SRC_DIR}:/home/ciq/src:rw} \
  --user=_ciq \
  --workdir=/home/ciq/src \
  local/connectiq-sdk:${CIQ_SDK_VERSION} \
  /bin/bash